### PR TITLE
Fix link to clj-kondo pod example

### PR DESCRIPTION
**Pull request by teodorlu**
I think the README was supposed to lead here?

### CODE REVIEW

**Comment by borkdude** [comment]
@teodorlu Thanks. I think this part of the README is generated using a script though, so is it possible to fix in the script which generates this?

**Comment by teodorlu** [comment]
I'll look into it :+1:

**Comment by teodorlu** [comment]
Looks like `script/derive-manifests.clj` simply hadn't been run. So I ran it.

After running it, I found some other inconsistencies between the README and the manifest files. I tried to fix what made sense.

Do you see anything that's still wrong / looks weird?

**Comment by teodorlu** [comment]
I also edited `derive-manifest.clj` not to run the side-effecting `insert-table!` function when run from a REPL.

https://github.com/teodorlu/pod-registry/blob/47a322911cefd8a01bed3e726e66f12e504f096e/script/derive-manifests.clj#L75-L76

**Comment by borkdude** [comment]
Thanks!

**Pull request merged**
