### PR TITLE
Fix lanterna links

### PR DESCRIPTION
**Pull request by mathisto**
Just a simple doc fix. It looks like the URL was left blank originally; I suspect it's okay to point it to the repo now. Additionally, the example link had a small typo.

### CODE REVIEW

**Comment by borkdude** [comment]
This part of the README is generated from the manifest files.

**Comment by mathisto** [comment]
Oooooh. Nice. Ok, let me take a peek. I just noticed that the link generated is to a CircleCI artifact which they purge after 30 days.

**Comment by borkdude** [comment]
This is correct, I think I should make a non-SNAPSHOT release.. let me add this to my list. I'll respond here once it's done.

**Comment by mathisto** [comment]
I fixed the typo in the manifest.

**Comment by borkdude** [comment]
And now you can run a script from the `script` directory that will populate the README, thanks!

**Comment by borkdude** [comment]
Thanks again. I'll take a look at those lanterna binaries soon.

**Comment by mathisto** [comment]
If you remember, hit me up when you do. I'll make another patch to update the `manifests/org.babashka/lanterna` folder and the `:pod/version` and `:pod/artifact` values.

**Comment by borkdude** [comment]
Published 0.0.1

**Pull request merged**
