### PR TITLE
Add atomisthq/docker pod for parsing dockerfiles

### PR DESCRIPTION
**Pull request by slimslenderslacks**
Use official docker golang libs to parse dockerfiles and image names See https://github.com/atomisthq/pod-babashka-docker

### CODE REVIEW

**Comment by borkdude** [comment]
@slimslenderslacks Thanks for creating this pod! 

The recommendation is to choose a name `pod-<your-org>-<lib>`. The name babashka is reserved for pods published by this organization. In your case, the suggested name would be: `pod-atomisthq-docker`. Also maybe the name `docker` would be too general. E.g. there was a pod before named [pod-lispyclouds-docker](https://github.com/lispyclouds/pod-lispyclouds-docker) which you could use for running docker images. But the library name is only a concern within an organization, so I'd be ok with whatever name.

cc @lispyclouds

**Comment by lispyclouds** [comment]
This is cool! I second naming it something a bit more specific but also would remark that as the author of pod-lispyclouds-docker I have no issues if something else uses the name too 😉. Its purpose has been superseded by [contajners](https://github.com/lispyclouds/contajners) and is deprecated now.

**Comment by slimslenderslacks** [comment]
Thanks both!  I've switched the org to be "atomisthq".  I'm having a hard time thinking of other names - I was thinking about moby but I don't think people associate the moby project with docker.

**Comment by lispyclouds** [comment]
How about pod-atomisthq-tools.docker maybe? Since this is more like a lib of tooling and more things could be added later too?

**Comment by slimslenderslacks** [comment]
good idea!

**Review by lispyclouds — APPROVED** [review]

**Comment by lispyclouds** [comment]
@slimslenderslacks just fyi, I added the [entry](https://github.com/babashka/pod-registry/commit/044ff1f53c779b346f700107b13ea61c5f45829a) to the readme as well, you could update this if and when you make updates to your pod. Thanks again!

**Pull request merged**
